version: "3.8" 

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:password@db:5432/tododb
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules:/app/node_modules
      - ./src:/app/src
    command: bash -c "npx prisma generate && npx prisma migrate dev --name init && npm install && npm run dev"

volumes:
  postgres-data:
